version: '3.8'

services:
  # Containerul care ruleaza analiza
  scanner:
    build: .
    container_name: phil-scanner-task
    volumes:
      - stock_data:/app
    restart: "no"

  # Containerul care afiseaza rezultatele (Interfata Web)
  web:
    image: nginx:alpine
    container_name: phil-web-ui
    ports:
      - "8080:80"
    volumes:
      - stock_data:/usr/share/nginx/html
    restart: always

volumes:
  stock_data:
